config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :problems, only: [ :create, :show ] 
  resources :days, only: [:index, :show]
  resources :solutions, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :problems
  has_many :solutions, through: :problems
  validates :date, uniqueness: true
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :day
  has_many :solutions
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :problem
  belongs_to :user

  validates :language, presence: true 
  validates :code, presence: true
  validate :code_works, on: :create

  private

  def code_works
    if self.language.downcase == "ruby"
      begin
        input = problem.test_input
        result = eval("def solution(input)\n" + self.code + "\n end")
        p solution(input)
        errors.add(:code, "doesn't pass") unless solution(input).to_i == problem.test_result.to_i
      rescue
        errors.add(:code, "doesn't work")
      end
    end 
  end
end

app/models/tested_solution.rb
class TestedSolution
  attr_accessor :input
  attr_accessor :answer
  attr_accessor :output

  
  def initialize(opt = {})
    @input = opt[:input]
    @answer = opt[:answer]
    @output = opt[:output]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @day = Day.find_by(date: Date.today)
    @new_problem = Problem.new
  end


end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  
  def show
    @problem = Problem.find(params[:id])
    if params[:tested_solution].present?
      @tested_solution = TestedSolution.new(input: params[:tested_solution][:input], answer: Solution.find(params[:tested_solution][:answer_id]))
      input = @tested_solution.input
      eval("def solution(input)\n" + self.code + "\n end")
      @tested_solution.output = solution(input)
    end
    @solution = Solution.new
  end

  def create
    @problem = Problem.new(problem_params)
    
    @problem.save
    redirect_to root_path, notice: "Saved"
  end

  private

  def problem_params
    params.require(:problem).permit(:description, :test_input, :test_result, :position, :day_id)
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController


  def create
    @solution = Solution.new(solution_params)
    @solution.code = @solution.code
    @solution.user = current_user
    @problem = @solution.problem
    if @solution.save
      redirect_to problem_path(@solution.problem)
    else 
      render 'problems/show'
    end
  end
  def destroy 
    @solution = Solution.find(params[:id])
    @solution.destroy
    redirect_to problem_path(@solution.problem)
  end
  
  private 

  def solution_params
    params.require(:solution).permit(:code, :comment, :language, :problem_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def kitt
      @user = User.from_kitt(request.env["omniauth.auth"])
      @contact_me = view_context.link_to(
        "contact Gkosmo",
        "slack://user?team=T02NE0241&id=U1LTDUQ4R",
        class: "underline"
      )

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        flash.notice = "Successfully signed in with Kitt!"
      else
        redirect_to root_path
        flash.alert = "For an unknown reason, we couldn't store your information in our database. Please #{@contact_me}."
      end

      def failure
        reason = request.env["omniauth.auth"]&.error_description
        redirect_to root_path
        flash.alert = "Failed to sign in with Kitt (Reason: #{reason || 'Unknown'}). If it persists, please #{@contact_me}."
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AocBxl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <p>today is <%= @day.date.strftime("%D") %> </p>

    <p> today problems: </p>

    <% @day.problems.sort_by(&:position).each do |problem|%>
        <%= render "problems/problem", problem: problem do %>
                <%= link_to "see the answers", problem_path(problem)%>
        <% end %>
    <% end%>

    <div data-controller="toggle-display">
        <span> Post todays problem: <i class="fas fa-pen" data-action="click->toggle-display#toggle"> </i> </span>
        <%= simple_form_for @new_problem, html: {"data-toggle-display-target" => "toggable", class: "d-none"} do |f| %>
            <%= f.input :description %>
            <%= f.input :test_input %>
            <%= f.input :test_result %>
            <%= f.input :position%>
            <%= f.input :day_id, as: :hidden, input_html: { value: @day.id } %>
            <%= f.submit %>
        <% end %>
    </div>
</div>

app/views/problems/_problem.html.erb
<div class="card">
    <div class="card-header"> Problem: <%= problem.position %> </div>
    <div class="card-body">
        <strong class="mx-1"> Description: </strong> <%= problem.description%>
        <%= yield %>
    </div>
    <div class="card-footer d-flex">
        <div class="input">
            <strong class="mx-1" > Test input:</strong > <%= problem.test_input %>
        </div>
        <div class="result">
            <strong class="mx-1"> Test result:</strong> <%= problem.test_result %>
        </div>
    </div>  
</div>

app/views/problems/show.html.erb
<div class="row my-2">
    <%= render "problems/problem", problem: @problem %>
</div>
<% if @tested_solution %>
    <h3>Solution for the given input: <%= @tested_solution.output %> </h3>
<% end %>
<div class="row my-2 d-flex justify-content-center">
     <div data-controller="toggle-display w-100">
        <span data-toggle-display-target="toggable"> Post an answer: </span><i class="fas fa-pen" data-action="click->toggle-display#toggle"> </i>
        <%= simple_form_for @solution, html: {"data-toggle-display-target" => "toggable", class: "#{'d-none' unless @solution.errors.any?} card p-2"}, remote: true do |f| %>
            <%= f.input :code, placeholder: "If you're code is in ruby, it should NOT be a function definition, but raw code with a return at the end",input_html: { rows: 8 } %>
            <%= f.input :language %>
            <%= f.input :comment %>
            <%= f.input :problem_id, as: :hidden, input_html: { value: @problem.id } %>
            <%= f.submit %>
        <% end %>
    </div>
</div>


<div class="my-2">
   
    <strong> Provided Answers: </strong>
    <div class="row">
        <% @problem.solutions.each do |answer| %>
            <div class="card col-12">
                <div class="card-header">
                    created at: <%= answer.created_at %>
                    <% if @tested_solution %>
                        <%= @tested_solution.present? %>
                        <h3>Solution for the given input: <%= @tested_solution.output %> </h3>
                    <% end %>
                </div>
                <div class="body d-flex justify-content-around">
                    <pre><code class="m-2">
                    <%= answer.code %> 
                    </code></pre>
                    <%= simple_form_for :tested_solution, url: problem_path(@problem), method: :get do |f| %>
                        <%= f.input :input, as: :text, label: "input to test", input_html: {value: (@tested_solution&.input || @problem.test_input) } %>
                        <%= f.input :answer_id, as: :hidden, input_html: {value: answer.id }%>
                        <%= f.submit %>
                    <% end %>
                </div>
                <div class="footer">
                    <% if current_user == answer.user %>
                        <%= link_to "delete", solution_path(answer), method: :delete%>
                    <% end %>
                </div>
            </div> 
        <% end %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>